function main_compare_drive_models()
%MAIN_COMPARE_DRIVE_MODELS Placeholder for future drive-model comparisons.
    error(['main_compare_drive_models is not implemented yet. ', ...
           'After the baseline prescribed-velocity model is working, ', ...
           'this entry point can compare pressure loading, moving walls, ', ...
           'pulse trains, and asymmetric timing models.']);
end
