function J = assemble_objective_function(metrics, weights)
%ASSEMBLE_OBJECTIVE_FUNCTION Combine compression and uniformity metrics.
    J = weights.rho * metrics.meanRho + ...
        weights.B * metrics.meanB - ...
        weights.uniformityRho * metrics.uniformityRho - ...
        weights.uniformityB * metrics.uniformityB - ...
        weights.coreSpeed * metrics.coreSpeed;
end
