function summary = summarize_run(history, cfg)
%SUMMARIZE_RUN Create a compact text summary for the finished run.
    if isempty(history.t)
        summary.message = sprintf('[%s] No time steps were taken.', cfg.caseName);
        return;
    end
    summary.message = sprintf(['[%s] completed %d steps to t = %.4f. ', ...
                               'Final core mean rho = %.4f, mean |B| = %.4f, ', ...
                               'rho nonuniformity = %.4e, |B| nonuniformity = %.4e.'], ...
                               cfg.caseName, history.step(end), history.t(end), ...
                               history.meanRho(end), history.meanB(end), ...
                               history.uniformityRho(end), history.uniformityB(end));
end
