function caseConfig = case_baseline_symmetric()
caseConfig = build_case_config();
caseConfig.runName = 'baseline_symmetric';
caseConfig.grid.Lx = 1.0;
caseConfig.grid.Ly = 1.0;
caseConfig.grid.Nx = 80;
caseConfig.grid.Ny = 80;
caseConfig.grid.ng = 2;
caseConfig.physics.gamma = 5/3;
caseConfig.physics.mu0   = 1.0;
caseConfig.physics.rho0  = 1.0;
caseConfig.physics.p0    = 1.0;
caseConfig.physics.v0    = [0.0, 0.0, 0.0];
caseConfig.physics.B0    = [1.0, 0.0, 0.0];
caseConfig.time.tEnd = 0.35;
caseConfig.time.cfl  = 0.35;
caseConfig.time.maxSteps = 20000;
caseConfig.drive.type = 'prescribed_velocity';
caseConfig.drive.parameters.boundaries = {'left','right','bottom','top'};
caseConfig.drive.parameters.amplitude_fraction_fast = 0.10;
caseConfig.drive.parameters.temporal_profile = 'smooth_sine_squared';
caseConfig.drive.parameters.tStart = 0.0;
caseConfig.drive.parameters.tStop  = 0.20;
caseConfig.drive.parameters.spatial_profile = 'uniform';
caseConfig.drive.parameters.tangential_rule = 'copy_from_interior';
caseConfig.output.makePlots = true;
caseConfig.output.writeData = false;
end
